# Generated by Django 4.2.16 on 2024-10-06 17:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='unique_verify_string',
            field=models.CharField(default=uuid.uuid4, max_length=256),
        ),
    ]
