# Generated by Django 4.2.16 on 2024-10-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_alter_customuser_unique_verify_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='passwordChangeField',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
