# Generated by Django 4.2.16 on 2024-10-16 20:59

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=500)),
                ('category', models.JSONField(blank=True, default=list)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('cover_img', cloudinary.models.CloudinaryField(default='ibhuo9ahkqa8kxbg211l', max_length=255, verbose_name='cover_img')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorprofile')),
            ],
        ),
    ]
