# Generated by Django 4.2.16 on 2024-10-14 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('healthCard', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('desc', models.TextField(blank=True, default=None, max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
