# Generated by Django 4.2.16 on 2024-10-14 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0002_alter_department_dept_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(blank=True, max_length=10, null=True)),
                ('specialist', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.TextField(blank=True, default=None, max_length=200, null=True)),
                ('degree', models.CharField(blank=True, max_length=200, null=True)),
                ('hospital', models.CharField(blank=True, max_length=150, null=True)),
                ('hospital_district', models.CharField(blank=True, max_length=150, null=True)),
                ('hospital_state', models.CharField(blank=True, max_length=150, null=True)),
                ('fees', models.CharField(blank=True, max_length=50, null=True)),
                ('avail', models.BooleanField(blank=True, default=False, null=True)),
                ('room_id', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
