# Generated by Django 4.2.16 on 2024-10-17 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('review', models.TextField(blank=True, max_length=200, null=True)),
                ('prescription', models.TextField(blank=True, max_length=200, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Waiting'), (1, 'Under Treatment'), (2, 'Checkup Done')], default=0)),
                ('prescribed_date', models.DateTimeField(blank=True, null=True)),
                ('pr_no', models.CharField(blank=True, default='--', max_length=40, null=True)),
                ('doctor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorprofile')),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientprofile')),
            ],
        ),
    ]
