# Generated by Django 4.2.16 on 2024-10-06 08:50

import autoslug.fields
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True)),
                ('dept_img', cloudinary.models.CloudinaryField(default='ibhuo9ahkqa8kxbg211l', max_length=255, verbose_name='department')),
            ],
        ),
    ]
