# Generated by Django 4.2.16 on 2024-10-06 09:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_img',
            field=cloudinary.models.CloudinaryField(default='jkicyfesnzkvgxqx9lve', max_length=255, verbose_name='department'),
        ),
    ]
